// Code generated by MockGen. DO NOT EDIT.
// Source: product_repository.go

// Package productrepository is a generated GoMock package.
package productrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	product "github.com/codepnw/mini-ecommerce/internal/product"
	gomock "github.com/golang/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// DecreaseStock mocks base method.
func (m *MockProductRepository) DecreaseStock(ctx context.Context, tx *sql.Tx, productID int64, qtyDecrease int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseStock", ctx, tx, productID, qtyDecrease)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecreaseStock indicates an expected call of DecreaseStock.
func (mr *MockProductRepositoryMockRecorder) DecreaseStock(ctx, tx, productID, qtyDecrease interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseStock", reflect.TypeOf((*MockProductRepository)(nil).DecreaseStock), ctx, tx, productID, qtyDecrease)
}

// Delete mocks base method.
func (m *MockProductRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockProductRepository) FindByID(ctx context.Context, id int64) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProductRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProductRepository)(nil).FindByID), ctx, id)
}

// FindByIDForUpdate mocks base method.
func (m *MockProductRepository) FindByIDForUpdate(ctx context.Context, tx *sql.Tx, id int64) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDForUpdate", ctx, tx, id)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDForUpdate indicates an expected call of FindByIDForUpdate.
func (mr *MockProductRepositoryMockRecorder) FindByIDForUpdate(ctx, tx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDForUpdate", reflect.TypeOf((*MockProductRepository)(nil).FindByIDForUpdate), ctx, tx, id)
}

// IncreaseStock mocks base method.
func (m *MockProductRepository) IncreaseStock(ctx context.Context, tx *sql.Tx, productID int64, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseStock", ctx, tx, productID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseStock indicates an expected call of IncreaseStock.
func (mr *MockProductRepositoryMockRecorder) IncreaseStock(ctx, tx, productID, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseStock", reflect.TypeOf((*MockProductRepository)(nil).IncreaseStock), ctx, tx, productID, quantity)
}

// Insert mocks base method.
func (m *MockProductRepository) Insert(ctx context.Context, input *product.Product) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, input)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockProductRepositoryMockRecorder) Insert(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockProductRepository)(nil).Insert), ctx, input)
}

// List mocks base method.
func (m *MockProductRepository) List(ctx context.Context, filter *product.ProductFilter) ([]*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProductRepositoryMockRecorder) List(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProductRepository)(nil).List), ctx, filter)
}

// SKUExists mocks base method.
func (m *MockProductRepository) SKUExists(ctx context.Context, sku string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SKUExists", ctx, sku)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SKUExists indicates an expected call of SKUExists.
func (mr *MockProductRepositoryMockRecorder) SKUExists(ctx, sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SKUExists", reflect.TypeOf((*MockProductRepository)(nil).SKUExists), ctx, sku)
}

// Update mocks base method.
func (m *MockProductRepository) Update(ctx context.Context, input *product.Product) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProductRepositoryMockRecorder) Update(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductRepository)(nil).Update), ctx, input)
}
