// Code generated by MockGen. DO NOT EDIT.
// Source: cart_repository.go

// Package cartrepository is a generated GoMock package.
package cartrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	cart "github.com/codepnw/mini-ecommerce/internal/cart"
	gomock "github.com/golang/mock/gomock"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// ClearCart mocks base method.
func (m *MockCartRepository) ClearCart(ctx context.Context, cartID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockCartRepositoryMockRecorder) ClearCart(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockCartRepository)(nil).ClearCart), ctx, cartID)
}

// GetCartItemDetails mocks base method.
func (m *MockCartRepository) GetCartItemDetails(ctx context.Context, cartItemID int64, cartID string) (*cart.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemDetails", ctx, cartItemID, cartID)
	ret0, _ := ret[0].(*cart.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemDetails indicates an expected call of GetCartItemDetails.
func (mr *MockCartRepositoryMockRecorder) GetCartItemDetails(ctx, cartItemID, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemDetails", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemDetails), ctx, cartItemID, cartID)
}

// GetCartItemForUpdate mocks base method.
func (m *MockCartRepository) GetCartItemForUpdate(ctx context.Context, tx *sql.Tx, cartItemID int64, cartID string) (*cart.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemForUpdate", ctx, tx, cartItemID, cartID)
	ret0, _ := ret[0].(*cart.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemForUpdate indicates an expected call of GetCartItemForUpdate.
func (mr *MockCartRepositoryMockRecorder) GetCartItemForUpdate(ctx, tx, cartItemID, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemForUpdate", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemForUpdate), ctx, tx, cartItemID, cartID)
}

// GetCartItems mocks base method.
func (m *MockCartRepository) GetCartItems(ctx context.Context, cartID string) ([]*CartItemDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItems", ctx, cartID)
	ret0, _ := ret[0].([]*CartItemDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItems indicates an expected call of GetCartItems.
func (mr *MockCartRepositoryMockRecorder) GetCartItems(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItems", reflect.TypeOf((*MockCartRepository)(nil).GetCartItems), ctx, cartID)
}

// GetOrCreateActiveCart mocks base method.
func (m *MockCartRepository) GetOrCreateActiveCart(ctx context.Context, userID sql.NullInt64, sessionID string) (*cart.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateActiveCart", ctx, userID, sessionID)
	ret0, _ := ret[0].(*cart.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateActiveCart indicates an expected call of GetOrCreateActiveCart.
func (mr *MockCartRepositoryMockRecorder) GetOrCreateActiveCart(ctx, userID, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateActiveCart", reflect.TypeOf((*MockCartRepository)(nil).GetOrCreateActiveCart), ctx, userID, sessionID)
}

// RemoveItem mocks base method.
func (m *MockCartRepository) RemoveItem(ctx context.Context, tx *sql.Tx, cartID string, cartItemID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, tx, cartID, cartItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockCartRepositoryMockRecorder) RemoveItem(ctx, tx, cartID, cartItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockCartRepository)(nil).RemoveItem), ctx, tx, cartID, cartItemID)
}

// UpdateItemQuantity mocks base method.
func (m *MockCartRepository) UpdateItemQuantity(ctx context.Context, tx *sql.Tx, cartID string, cartItemID int64, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemQuantity", ctx, tx, cartID, cartItemID, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemQuantity indicates an expected call of UpdateItemQuantity.
func (mr *MockCartRepositoryMockRecorder) UpdateItemQuantity(ctx, tx, cartID, cartItemID, quantity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemQuantity", reflect.TypeOf((*MockCartRepository)(nil).UpdateItemQuantity), ctx, tx, cartID, cartItemID, quantity)
}

// UpsertItem mocks base method.
func (m *MockCartRepository) UpsertItem(ctx context.Context, tx *sql.Tx, item *cart.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertItem", ctx, tx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertItem indicates an expected call of UpsertItem.
func (mr *MockCartRepositoryMockRecorder) UpsertItem(ctx, tx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertItem", reflect.TypeOf((*MockCartRepository)(nil).UpsertItem), ctx, tx, item)
}
